[build-system]
requires = ["setuptools >= 61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "virtual_ship"
description = "Code for the Virtual Ship Classroom, where Marine Scientists can combine Copernicus Marine Data with an OceanParcels ship to go on a virtual expedition."
readme = "README.md"
dynamic = ["version"]
authors = [{ name = "oceanparcels.org team" }]
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Education",
    "Intended Audience :: Education",
]
dependencies = [
    "shapely >= 2, < 3",
    "pyproj >= 3, < 4",
    "parcels >= 3, < 4",
    "scipy >= 1, < 2",
    "xarray >= 2023, < 2024",
    # The packages below are parcels packages not included in their distribution requirements.
    "numpy >= 1, < 2",
    "cgen >= 2020, < 2021",
    "dask >= 2023, < 2025",
    "cftime >= 1, < 2",
    "psutil >= 1, < 2",
    "netCDF4 >= 1, < 2",
    "zarr >= 2, < 3",
    "tqdm >= 4, < 5",
    "pymbolic >= 2022, < 2023",
]

[project.urls]
homepage = "https://oceanparcels.org/"
repository = "https://github.com/OceanParcels/Virtual_ship_classroom"
tracker = "https://github.com/OceanParcels/Virtual_ship_classroom/issues"

[tool.setuptools]
packages = ["virtual_ship"]

[tool.setuptools_scm]
write_to = "virtual_ship/_version_setup.py"
local_scheme = "no-local-version"

[project.optional-dependencies]
dev = [
    "black == 24.4.0",
    "darglint == 1.8.1",
    "flake8 == 7.0.0",
    "Flake8-pyproject == 1.2.3",
    "isort == 5.13.2",
    "pydocstyle == 6.3.0",
    "sort-all == 1.2.0",
    "pytest == 8.2.0",
    "pytest-cov == 5.0.0",
    "codecov == 2.1.13",
    "sortedcontainers == 2.4.0",
    "sortedcontainers-stubs == 2.4.2",
]

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.flake8]
extend-ignore = "E501"     # Don't check line length.
docstring_style = "sphinx" # Use sphinx docstring style for darglint plugin.
