name: ci

on: [push, pull_request]

env:
  PACKAGE: virtual_ship

jobs:
  codetools:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: pip install ".[dev]"
      - name: flake8
        run: flake8 ./$PACKAGE
      - name: pydocstyle
        run: pydocstyle ./$PACKAGE
      - name: sort-all
        run: |
          find ./$PACKAGE -type f -name '__init__.py' -print0 | xargs -0 sort-all
          [[ -z $(git status -s) ]]
          git checkout -- .
      - name: black
        run: black --diff --check ./$PACKAGE
      - name: isort
        run: isort --check-only --diff ./$PACKAGE

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: install
        run: pip install ".[dev]"
      - name: run_tests
        run: pytest --cov=virtual_ship tests
